### ISSUE TITLE
msDataTab

### ISSUE THREAD

**Issue by lgatto** [lgatto/RforProteomics#12]
The MS data table currently looks like this.

|Data type      |File format          |Data structure                             |Package                       |
|:--------------|:--------------------|:------------------------------------------|:-----------------------------|
|Raw            |mzXML or mzML        |mzRpwiz or mzRramp                         |mzR                           |
|Raw            |mzXML or mzML        |List of MassSpectrum objects               |MALDIquantForeign             |
|Identification |mzIdentML            |mzRident                                   |mzR                           |
|Identification |mzIdentML            |mzID                                       |mzID                          |
|Quantitative   |mzTab                |MSnSet                                     |MSnbase                       |
|Raw            |mzXML or mzML        |MSnExp                                     |MSnbase                       |
|Peak lists     |mgf                  |MSnExp                                     |MSnbase                       |
|Imaging        |imzML or Analyze 7.5 |MSImageSet or list of MassSpectrum objects |Cardinal or MALDIquantForeign |

@sgibb could you split `Cardinal` and `MALDIquantForeign` on two different lines, as I have done for raw data, as the table becomes unnecessary wide like it is now (see the chapter for example).

**Comment by sgibb** [comment]
Done, now the table has the following format:

|Data type      |File format          |Data structure               |Package           |
|:--------------|:--------------------|:----------------------------|:-----------------|
|Raw            |mzXML or mzML        |mzRpwiz or mzRramp           |mzR               |
|Raw            |mzXML or mzML        |list of MassSpectrum objects |MALDIquantForeign |
|Identification |mzIdentML            |mzRident                     |mzR               |
|Identification |mzIdentML            |mzID                         |mzID              |
|Quantitative   |mzTab                |MSnSet                       |MSnbase           |
|Raw            |mzXML or mzML        |MSnExp                       |MSnbase           |
|Peak lists     |mgf                  |MSnExp                       |MSnbase           |
|Imaging        |imzML or Analyze 7.5 |MSImageSet                   |Cardinal          |
|Imaging        |imzML or Analyze 7.5 |list of MassSpectrum objects |MALDIquantForeign |

@lgatto I would suggest to move the "Raw" row of MSnbase to the top. Then all "Raw" rows are grouped together. Or do you prefer to group by package?

**Comment by lgatto** [comment]
Thanks!

|Data type      |File format          |Data structure               |Package           |
|:--------------|:--------------------|:----------------------------|:-----------------|
|Raw            |mzXML or mzML        |mzRpwiz or mzRramp           |mzR               |
|Raw            |mzXML or mzML        |list of MassSpectrum objects |MALDIquantForeign |
|Raw            |mzXML or mzML        |MSnExp                       |mzR               |
|Identification |mzIdentML            |mzRident                     |MSnbase           |
|Identification |mzIdentML            |mzID                         |mzID              |
|Quantitative   |mzTab                |MSnSet                       |MSnbase           |
|Peak lists     |mgf                  |MSnExp                       |MSnbase           |
|Imaging        |imzML or Analyze 7.5 |MSImageSet                   |Cardinal          |
|Imaging        |imzML or Analyze 7.5 |list of MassSpectrum objects |MALDIquantForeign |
